export const START_DOCUMENT_ACTION = "START_DOCUMENT_ACTION"
export const DOCUMENT_ACTION_SUCCESS = "DOCUMENT_ACTION_SUCCESS"
export const DOCUMENT_ACTION_FAILURE = "DOCUMENT_ACTION_FAILURE"
export const GET_ALL_DOCUMENTS = "GET_ALL_DOCUMENTS"
export const CREATE_DOCUMENT = "CREATE_DOCUMENT"
export const SELECT_DOCUMENT = "SELECT_DOCUMENT"
export const SET_COUNT = "SET_COUNT"




